export const TRADING_PHRASES: string[] = [
  "Analisando padrão de candlestick em M5...",
  "Suporte testado em 1.0832 — pressão compradora.",
  "RSI sobrevendido: aguardando confirmação.",
  "Volume crescente no rompimento de resistência.",
  "Médias móveis em cruzamento de alta (golden cross).",
  "Fibonacci 61.8% sustentando o pullback.",
  "Setup 9.1 confirmado — gerenciamento ativo.",
  "Banca: priorize gestão sobre acertos.",
  "Stop loss é seguro, não fraqueza.",
  "Não brigue com a tendência principal.",
  "Operando assertividade > frequência.",
  "Alvo parcial atingido — protegendo lucro.",
  "Disciplina diária é o verdadeiro edge.",
  "Notícia de alto impacto em 5min — aguardar.",
  "Spread alargado: cuidado com slippage.",
  "Liquidez retornando ao mercado europeu.",
  "EUR/USD rompeu canal de baixa.",
  "Padrão pin bar rejeitando topo.",
  "Engolfo de baixa em zona de oferta.",
  "Operação encerrada no break-even.",
  "Risco/retorno mínimo de 1:2 sempre.",
  "Backtest do mês: 67% de assertividade.",
  "Drawdown controlado dentro do limite.",
  "Ciclo de Wyckoff em fase de markup.",
  "Volume de interesse aberto crescente.",
  "Bandas de Bollinger comprimindo.",
  "Squeeze prestes a explodir volatilidade.",
  "MACD divergindo do preço — atenção.",
  "Trade plan ativo — sem improvisos.",
  "Mind the gap: abertura assimétrica.",
  "Sessão asiática com baixa volatilidade.",
  "Sessão de Londres abrindo — atenção.",
  "Overlap NY/Londres: maior liquidez.",
  "Encerrando posições antes do FOMC.",
  "Diário de trade atualizado.",
  "Revisão semanal: ajustes no risco.",
  "Capital protegido > capital arriscado.",
  "Não opere sem plano definido.",
  "Padrão ABCD identificado em H1.",
  "Onda 3 de Elliott em desenvolvimento.",
  "Order block respeitado novamente.",
  "Imbalance preenchido — entrada possível.",
  "Liquidity grab em mínima recente.",
  "BOS confirmado: estrutura de alta.",
  "CHoCH detectado — mudança de caráter.",
  "POC do dia funcionando como suporte.",
  "VWAP sendo respeitado pelo preço.",
  "Footprint mostra absorção compradora.",
  "Delta positivo dominando o leilão.",
  "Tape reading: agressão vendedora cai.",
  "Reversão à média: oportunidade pontual.",
  "Operação por contexto, não por sinal.",
  "Confirmação > antecipação.",
  "Esperando candle de força para entrar.",
  "Exit strategy definida antes da entrada.",
  "Trailing stop ativado em 50% do alvo.",
  "Pullback saudável para continuação.",
  "Topo duplo invalidado por rompimento.",
  "Cunha ascendente próxima do clímax.",
  "Triângulo simétrico em compressão final.",
  "Bandeira de alta após impulso forte.",
  "Cup & handle formado em D1.",
  "Three white soldiers no gráfico.",
  "Hammer de reversão em zona-chave.",
  "Doji indica indecisão — aguardar.",
  "Operação cancelada: contexto mudou.",
  "Disciplina é o edge real do trader.",
  "Sem ego, sem prejuízo emocional.",
  "Mercado paga a paciência.",
  "O setup é o mesmo, o resultado varia.",
  "Estatística > intuição.",
  "Gerencie o risco, o lucro se cuida.",
  "Foco no processo, não no resultado.",
];
